config/routes.rb
Rails.application.routes.draw do
  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout

  resources :user_sessions, only: [:new, :create]
  resources :mailbox, :collection => {:trash => :get}

  resources :sent

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :coordinator_profiles

  resources :client_profiles

  resources :notifications

  resources :folders

  resources :message_copies

  resources :messages => {:reply => :get, :forward => :get, :reply_all => :get, :undelete => :put}

  resources :attachements

  resources :ratings

  resources :courses

  resources :institutions

  resources :applications

  resources :users
  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/application.rb
class Application < ActiveRecord::Base
	# relationships
	has_many :attachements
	belongs_to :user
	belongs_to :institution
	belongs_to :course

    # user_id validations
	validates :user_id, presence: true
	# course_id validations
	validates :course_id, presence: true
	# hl_degree validations
	validates :hl_degree,presence: true,
	                     length: {maximum: 100}
	# hld_date validations
	validates :hld_date, presence: true
	validate do
      self.errors[:hld_date] << "must be a valid date" unless (DateTime.parse(self.hld_date) rescue false)
    end
    # address validations
	validates :address, presence: true,
	                   length: {maximum: 100}
	# state validations
	validates :state, presence: true,
	                  length: {maximum: 8}
	# institution_id validations
	validates :institution_id, presence: true
    
	scope :sent, lambda {where(:state => "sent")}
	scope :recieved, lambda {where(:state => "recieved")}
	scope :accepted, lambda {where(:state => "accepted")}
	scope :sorted, lambda { order("applications.position ASC") }
	scope :newest_first, lambda { order("applications.created_at DESC") }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  
  def logged_in?
    current_user
  end
  helper_method :logged_in?

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    elsif cookies.permanent.signed[:remember_me_token]
      verification = Rails.application.message_verifier(:remember_me).verify(cookies.permanent.signed[:remember_me_token])
      if verification
        Rails.logger.info "Logging in by cookie."
        @current_user ||= User.find(verification)
      end
    end
  end
  helper_method :current_user

  def require_user
    if current_user
      true
    else
      redirect_to new_user_session_path, notice: "You must be logged in to access that page."
    end
  end

end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: [:show, :edit, :update, :destroy]

  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.all
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
  end

  # GET /applications/new
  def new
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(application_params)
    if @application.save
      redirect_to @application, notice: 'Application was successfully created.'
    else
      render :new 
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url, notice: 'Application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      params.require(:application).permit(:user_id, :hl_degree, :hld_date, :address, :state, :institution_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_form.html.erb
<%= form_for(@application) do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :hl_degree %><br>
    <%= f.text_field :hl_degree %>
  </div>
  <div class="field">
    <%= f.label :hld_date %><br>
    <%= f.datetime_select :hld_date %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :institution_id %><br>
    <%= f.number_field :institution_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1>Editing Application</h1>

<%= render 'form' %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Applications</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Hl degree</th>
      <th>Hld date</th>
      <th>Address</th>
      <th>State</th>
      <th>Institution</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= application.user_id %></td>
        <td><%= application.hl_degree %></td>
        <td><%= application.hld_date %></td>
        <td><%= application.address %></td>
        <td><%= application.state %></td>
        <td><%= application.institution_id %></td>
        <td><%= link_to 'Show', application %></td>
        <td><%= link_to 'Edit', edit_application_path(application) %></td>
        <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Application', new_application_path %>

app/views/applications/new.html.erb
<h1>New Application</h1>

<%= render 'form' %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @application.user_id %>
</p>

<p>
  <strong>Hl degree:</strong>
  <%= @application.hl_degree %>
</p>

<p>
  <strong>Hld date:</strong>
  <%= @application.hld_date %>
</p>

<p>
  <strong>Address:</strong>
  <%= @application.address %>
</p>

<p>
  <strong>State:</strong>
  <%= @application.state %>
</p>

<p>
  <strong>Institution:</strong>
  <%= @application.institution_id %>
</p>

<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>