config/routes.rb
Rails.application.routes.draw do
  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout

  resources :user_sessions, only: [:new, :create]
  resources :mailbox, :collection => {:trash => :get}

  resources :sent

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :coordinator_profiles

  resources :client_profiles

  resources :notifications

  resources :folders

  resources :message_copies

  resources :messages => {:reply => :get, :forward => :get, :reply_all => :get, :undelete => :put}

  resources :attachements

  resources :ratings

  resources :courses

  resources :institutions

  resources :applications

  resources :users
  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/notification.rb
class Notification < ActiveRecord::Base
	#relationships
	belongs_to :user, :foreign_key => "recipient_id"
	#validations
     
    #Notification user_recipient_id validations

    validates :recipient_id, :presence => { :message => "The recipient_id is missing"},
                             :numericality => { only_integer: true, message: "the recipient id can only be an integer"}
	#Notification body validations
	validates :body, :presence => { message: "The notification's body can't be blank" }
    
    #Notification header validations                
	validates :header, :presence => { :message => "A notification must have a header"},
	                   :length => {:maximum => 255}


end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:recipient_id, :type, :body, :header)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recipient_id %><br>
    <%= f.number_field :recipient_id %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.number_field :type %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :header %><br>
    <%= f.text_field :header %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notifications</h1>

<table>
  <thead>
    <tr>
      <th>Recipient</th>
      <th>Type</th>
      <th>Body</th>
      <th>Header</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.recipient_id %></td>
        <td><%= notification.type %></td>
        <td><%= notification.body %></td>
        <td><%= notification.header %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recipient:</strong>
  <%= @notification.recipient_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @notification.type %>
</p>

<p>
  <strong>Body:</strong>
  <%= @notification.body %>
</p>

<p>
  <strong>Header:</strong>
  <%= @notification.header %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>