config/routes.rb
Rails.application.routes.draw do
  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout

  resources :user_sessions, only: [:new, :create]
  resources :mailbox, :collection => {:trash => :get}

  resources :sent

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :coordinator_profiles

  resources :client_profiles

  resources :notifications

  resources :folders

  resources :message_copies

  resources :messages => {:reply => :get, :forward => :get, :reply_all => :get, :undelete => :put}

  resources :attachements

  resources :ratings

  resources :courses

  resources :institutions

  resources :applications

  resources :users
  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/rating.rb
class Rating < ActiveRecord::Base
	#relationships
	belongs_to :institution
	belongs_to :user

	#validations
    
    #rating institution id validations
    validates :institution_id, :presence => { :message=> "The institution_id is missing"},
                               :numericality => { only_integer: true, :message => "the institution_id can only be an integer"}

    #rating user id validations
    validates :user_id, :presence => { :message => "The user_id is missing"}, 
                        :numericality => { only_integer: true, :message => "the user_id can only be an integer"}                         
    #rating value validations
    validates :value, :presence => { :message => "the rating value is missing"},
                      :numericality => true
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]

  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:institution_id, :user_id, :value)
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :institution_id %><br>
    <%= f.number_field :institution_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ratings</h1>

<table>
  <thead>
    <tr>
      <th>Institution</th>
      <th>User</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.institution_id %></td>
        <td><%= rating.user_id %></td>
        <td><%= rating.value %></td>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form' %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Institution:</strong>
  <%= @rating.institution_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @rating.user_id %>
</p>

<p>
  <strong>Value:</strong>
  <%= @rating.value %>
</p>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>