config/routes.rb
Rails.application.routes.draw do
  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout

  resources :user_sessions, only: [:new, :create]
  resources :mailbox, :collection => {:trash => :get}

  resources :sent

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :coordinator_profiles

  resources :client_profiles

  resources :notifications

  resources :folders

  resources :message_copies

  resources :messages => {:reply => :get, :forward => :get, :reply_all => :get, :undelete => :put}

  resources :attachements

  resources :ratings

  resources :courses

  resources :institutions

  resources :applications

  resources :users
  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/coordinator_profile.rb
class CoordinatorProfile < ActiveRecord::Base
	#relationships
	belongs_to :user
	belongs_to :institution
    
    #needed constants
     LEVEL_CHOICES = ['Bachelor','Masters','PHD']
     EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

	#validations begins
    
    validates :user_id, :presence => { :message => "The user_id is missing" },
                       :numericality => { only_integer: true, message: "The user_id can only be an integer" }

     
    validates :institution_id, :presence => { :message => "The institution_id is missing" },
                              :numericality => { only_integer: true, message: "The institution_id can only be an integer" }
    
    validates :level, :presence => { :message => "The institution_id can only be an integer" },
                      :inclusion => { :in => LEVEL_CHOICES, :message => "The level can only be Bachelor,Masters or PHD" }

    validates :email, :presence => { :message => "The email is missing" },
                      :length => { :maximum => 100 },
                      :format => EMAIL_REGEX,
                      :confirmation => true
	#validations ends


end

app/controllers/coordinator_profiles_controller.rb
class CoordinatorProfilesController < ApplicationController
  before_action :set_coordinator_profile, only: [:show, :edit, :update, :destroy]

  # GET /coordinator_profiles
  # GET /coordinator_profiles.json
  def index
    @coordinator_profiles = CoordinatorProfile.all
  end

  # GET /coordinator_profiles/1
  # GET /coordinator_profiles/1.json
  def show
  end

  # GET /coordinator_profiles/new
  def new
    @coordinator_profile = CoordinatorProfile.new
  end

  # GET /coordinator_profiles/1/edit
  def edit
  end

  # POST /coordinator_profiles
  # POST /coordinator_profiles.json
  def create
    @coordinator_profile = CoordinatorProfile.new(coordinator_profile_params)

    respond_to do |format|
      if @coordinator_profile.save
        format.html { redirect_to @coordinator_profile, notice: 'Coordinator profile was successfully created.' }
        format.json { render :show, status: :created, location: @coordinator_profile }
      else
        format.html { render :new }
        format.json { render json: @coordinator_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coordinator_profiles/1
  # PATCH/PUT /coordinator_profiles/1.json
  def update
    respond_to do |format|
      if @coordinator_profile.update(coordinator_profile_params)
        format.html { redirect_to @coordinator_profile, notice: 'Coordinator profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @coordinator_profile }
      else
        format.html { render :edit }
        format.json { render json: @coordinator_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coordinator_profiles/1
  # DELETE /coordinator_profiles/1.json
  def destroy
    @coordinator_profile.destroy
    respond_to do |format|
      format.html { redirect_to coordinator_profiles_url, notice: 'Coordinator profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coordinator_profile
      @coordinator_profile = CoordinatorProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coordinator_profile_params
      params.require(:coordinator_profile).permit(:user_id, :institution_id, :level)
    end
end

app/helpers/coordinator_profiles_helper.rb
module CoordinatorProfilesHelper
end

app/views/coordinator_profiles/_form.html.erb
<%= form_for(@coordinator_profile) do |f| %>
  <% if @coordinator_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coordinator_profile.errors.count, "error") %> prohibited this coordinator_profile from being saved:</h2>

      <ul>
      <% @coordinator_profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :institution_id %><br>
    <%= f.number_field :institution_id %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.number_field :level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coordinator_profiles/edit.html.erb
<h1>Editing Coordinator Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @coordinator_profile %> |
<%= link_to 'Back', coordinator_profiles_path %>

app/views/coordinator_profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Coordinator Profiles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Institution</th>
      <th>Level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coordinator_profiles.each do |coordinator_profile| %>
      <tr>
        <td><%= coordinator_profile.user_id %></td>
        <td><%= coordinator_profile.institution_id %></td>
        <td><%= coordinator_profile.level %></td>
        <td><%= link_to 'Show', coordinator_profile %></td>
        <td><%= link_to 'Edit', edit_coordinator_profile_path(coordinator_profile) %></td>
        <td><%= link_to 'Destroy', coordinator_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coordinator profile', new_coordinator_profile_path %>

app/views/coordinator_profiles/new.html.erb
<h1>New Coordinator Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', coordinator_profiles_path %>

app/views/coordinator_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @coordinator_profile.user_id %>
</p>

<p>
  <strong>Institution:</strong>
  <%= @coordinator_profile.institution_id %>
</p>

<p>
  <strong>Level:</strong>
  <%= @coordinator_profile.level %>
</p>

<%= link_to 'Edit', edit_coordinator_profile_path(@coordinator_profile) %> |
<%= link_to 'Back', coordinator_profiles_path %>